project:
  type: website

website:
  title: "Ita Ćirović Donev"
  reader-mode: true
  open-graph: true
  page-navigation: true
  back-to-top-navigation: true
  navbar:
    pinned: true
    #background: "#FBF9F7"
    right:
      - about.qmd
      - icon: github
        href: https://github.com/itacdonev
      - icon: twitter
        href: https://twitter.com/itacdonevFM
      - icon: linkedin
        href: https://www.linkedin.com/in/ita-cirovic-donev-9821379/
  # sidebar:
  #     title: Posts
  #     pinned: true
  #     collapse-level: 1
  #     style: docked
  #     contents: posts/**
  page-footer: 
    left: "Copyright 2022, Ita Ćirović Donev"
    right:
      - icon: github
        href: https://github.com/itacdonev
      - icon: twitter 
        href: https://twitter.com/itacdonevFM
      - icon: linkedin
        href: https://www.linkedin.com/in/ita-cirovic-donev-9821379/
    border: false
    
format:
  html:
    smooth-scroll: true
    theme: 
      light: spacelab #flatly
      #dark: darkly
    css: styles.css
    highlight-style: breeze #arrow-light
    description-meta: Applied ML learning journey
    toc: true
    toc-title: "Contents"