project:
  type: website

website:
  title: "Ita Ćirović Donev"
  navbar:
    #background: "#FBF9F7"
    right:
      - about.qmd
      - icon: github
        href: https://github.com/itacdonev
      - icon: twitter
        href: https://twitter.com/itacdonevFM
      - icon: linkedin
        href: https://www.linkedin.com/in/ita-cirovic-donev-9821379/
  page-footer: 
    left: "Copyright 2022, Ita Ćirović Donev"
    right:
      - icon: github
        href: https://github.com/itacdonev
      - icon: twitter 
        href: https://twitter.com/itacdonevFM
      - icon: linkedin
        href: https://www.linkedin.com/in/ita-cirovic-donev-9821379/
    border: false
    
format:
  html:
    smooth-scroll: true
    theme: 
      light: flatly
      #dark: darkly
    css: styles.css
    highlight-style: arrow-light
    description-meta: Applied ML learning journey
    