---
title: "Science diplomacy, a new field?"
subtitle: "Book Review: Letters from an Astrophysicist by Neil deGrasse Tyson"
author: "Ita Cirovic Donev"
date: "2020-01-16"
categories: [book review]
title-block-banner: true
#image: 
draft: true # Don't include in the listing, site map or site search
---

A new book by Neil deGrasse Tyson always lures me back into the bookstore, and this one is no exception. Letters from an Astrophysicist provides a structurally different book. Here we are privileged to get a view of multidimensional opinions and questions swirling around in our society, paired together with answers which embrace science diplomacy at its best. And all of this in an almost forgotten practice of correspondence of letter writing.

The correspondence is a presentation of numerous letters, received over the years, divided into four sections:

- Ethos (The characteristic spirit of culture, manifested in its beliefs and aspirations),
- Cosmos (The Universe seen as a well-ordered whole),
- Pathos (A plaintive appeal to emotions that already reside within us), and
- Kairos (A propitious moment for decision or action).

These are then further segmented into topics such as hope, IQ, parenting, science denial, school days, UFOs, etc. All of the questions are unique in their way and given their subject matter. For example, from the segment science denial, we have "Where is the proof?", in which the word proof relates to evolution and the age of the physical universe. The answer dr. Tyson gave here is very to the point, providing enough scientific (non-controversial) information to move from denial to an actual question, which hopefully further leads to research and widening personal information bucket. "Lego" blocks inching upwards.

My biggest takeaway from the book is the nature, structure, and the appropriateness of responses. There are times we can find ourselves in situations where our audience does not share the same opinion about the topic at hand, which can stir emotions on either side. With the advent of social media, these experiences increase manifold. Dr. Tyson enriches the reader with many diverse angles of human thinking and provides a measured, lucid, and leveled response, proving yet again to be a great teacher, not just of science, but of how to be human. This book will provide you with the numerous ways for communication exchanges to continue and end amicably, regardless of which belief, knowledge, or point of view you or your audience is coming from.

The prologue and epilogue provide yet another, even more personal, take on what it takes to succeed in life. The prologue is like a "memoir" of dr. Tyson's life path, while the epilogue is a "eulogy" to his father. Both are genuinely fascinating and emotional. To "translate" the words, I would say that I see it as a track race with hurdles in which one doesn't turn back, having regrets or pointing the blame for experiences, because the next hurdle is coming. Just look straight and keep moving.

The book was fun to read, refreshing, entertaining, while not requiring previous knowledge in astrophysics. There are many excellent and thoughtful quotes one can get from this book, but for me, this one is the strongest because it supersedes the other ones.

> "Failure is common to us all. But ambitious people use their failures as lessons to heed, as they push forward toward their goals. Don't fear change. Don't fear failure. The only thing to fear is loss of ambition."
Quotes

> "One objective reality is that our government doesn't work, not because we have dysfunctional voters. As a scientist and educator, my goal, then, is not to become President and lead a dysfunctional electorate, but to enlighten the electorate so they might choose the right leaders in the first place."

### References

Tyson, N. D. G. (2019). Letters from an astrophysicist. New York: W. W. Norton & Company.