---
title: "Python and Machine Learning"
subtitle: "A collection of most useful commands for doing machine learning using Python"
author: "Ita Cirovic Donev"
date: "2022-11-10"
categories: [python]
title-block-banner: true
#image: 
draft: true # Don't include in the listing, site map or site search
---

# Anaconda environment
Main steps and functions to define the anaconda environment and use it throughout the project.

**Create new empty environment**
```{bash}
conda create --name my_environment_name
```

**Create a copy of existing environment**
```{bash}
conda create -n my_environment_name
```

Copy an environment `conda create -n flowers --clone snowflakes`

Delete the environment `conda remove --name my_env_name --all`

Copy an environment `conda create -n flowers --clone snowflakes`

# Python

## Generators

- We can not iterate ove a generator more than once. However, we can make a copy of it using `tee` from the `itertools` library.

```{python}
from itertools import tee

gen1, gen2 = tee(my_generator)
```

# Mastering Pandas

**Problem: When we are dealing with time and id variables in the sense that there should be only one occurrence of information per specific time period for a given ID, how can we easily check that this is so in our dataframe.**

**Example: In finance, we usually have client_id and account_id........**

```
# Define which columns to check
cols_to_check = [i for i in mydf.columns if i not in cols_to_exclude]

# Initialize a list to store nonunique columns
nounq_cols = []

# Iterate through cols_to_check
for col in cols:
    if (mydf.groupby(['ID', 'ACC_ID', 'DATE'])\
        [col].nunique() != 1).any():
        nounq_cols.append(col)

print(f"Columns which have multiple ACC_IDs: \n{nounq_cols}")
```
